global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'mss-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

# Alertmanager
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
  
# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'dockerd-exporter'
    dns_sd_configs:
      - names:
        - 'tasks.dockerd-exporter'
        type: 'A'
        port: 9323

  - job_name: 'cadvisor'
    dns_sd_configs:
      - names:
        - 'tasks.cadvisor'
        type: 'A'
        port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
      - names:
        - 'tasks.node-exporter'
        type: 'A'
        port: 9100
  
  - job_name: 'node-linux'
    scrape_interval: 15s
    static_configs:
      - targets: ['nodeexporter-58:9100','172.16.9.51:9100']

  - job_name: 'cadvisor-58'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor-58:8080']

  - job_name: 'node-windows'
    scrape_interval: 15s
    static_configs:
      - targets: ['172.16.9.52:9182','172.16.9.57:9182']	  
  
  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'solr'
    scrape_interval: 15s
    static_configs:
      - targets: ['solr-1:9854']

  - job_name: 'postgres'
    scrape_interval: 15s
    static_configs:
      - targets: ['172.16.9.58:9187']

  - job_name: 'apache'
    scrape_interval: 15s
    static_configs:
      - targets: ['172.16.9.51:9117']

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
