FROM centos:7

MAINTAINER "Justyle" <vu.nguyenvan86@gmail.com>

### Update
RUN yum -y update; yum clean all
RUN yum -y install sudo epel-release; yum clean all
RUN yum install -y supervisor psmisc wget tar; yum clean all

### Set Time
RUN ln -sf /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime

### Install Java
WORKDIR /build
#COPY ./config/jdk-8u181-linux-x64.tar.gz /build/jdk-8u181-linux-x64.tar.gz
RUN wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u181-b13/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u181-linux-x64.tar.gz"
RUN tar vxzf jdk-8u181-linux-x64.tar.gz && \
    ln -s jdk1.8.0_181 java && \
    cd /build/java/ && \
    alternatives --install /usr/bin/java java /build/java/bin/java 2 && \
    alternatives --install /usr/bin/jar jar /build/java/bin/jar 2 && \
    alternatives --install /usr/bin/javac javac /build/java/bin/javac 2 && \
    alternatives --install /usr/bin/javaws javaws /build/java/bin/javaws 2 && \
    alternatives --set jar /build/java/bin/jar && \
    alternatives --set javac /build/java/bin/javac && \
    alternatives --set javaws /build/java/bin/javaws && \
    export JAVA_HOME=/build/java && \
    export JRE_HOME=/build/java/jre && \
    export PATH=$PATH:/build/java/bin:/build/java/jre/bin && \
    rm -f /build/jdk-8u181-linux-x64.tar.gz

ADD config/java.sh /etc/profile.d/java.sh
RUN chmod +x /etc/profile.d/java.sh && \
    source /etc/profile.d/java.sh

### Install Elasticsearch
RUN useradd elasticsearch -d /build/elasticsearch -s /sbin/nologin
RUN wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.11.tar.gz
RUN tar xzvf elasticsearch-5.6.11.tar.gz
RUN mv elasticsearch-5.6.11/* /build/elasticsearch
RUN rm -rf elasticsearch-5.6.11*
RUN chown elasticsearch.elasticsearch -R /build/elasticsearch/*
RUN mkdir -p /datavolume/data /datavolume/logs
RUN chown elasticsearch.elasticsearch -R /datavolume/*

### Install plugin X-Pack
#RUN /build/elasticsearch/bin/elasticsearch-plugin install x-pack

### Remove packages
RUN yum autoremove -y

### Apply Supervisor configuration
ADD config/elasticsearch-supervisor.ini /etc/supervisord.d/elasticsearch.ini
ADD config/start_supervisor.sh /build/start_supervisor.sh
RUN chmod u=rwx /build/start_supervisor.sh

### WORK DIR
WORKDIR /build/elasticsearch

### DATA VOLUMES
VOLUME ["/datavolume"]

### PORTS
EXPOSE 9200
EXPOSE 9300

### USER
#USER elasticsearch

### CMD
ENTRYPOINT ["/build/start_supervisor.sh"]
