version: '3.3'

volumes:
  elasticsearch.data.1:
    external: true
  elasticsearch.data.2:
    external: true
networks:
  mss-network:
    external:
      name: mss-network

services:

  elasticsearch:
    image: elasticsearch:5.6.11
    hostname: mss-elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=mss-cluster
      - node.name=mss-elasticsearch
      - node.master=false
      - node.data=false
      - node.ingest=false
      #- bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=3
      - discovery.zen.ping.unicast.hosts=mss-elasticsearch-master
      - http_max_content_length=1204MB
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    networks:
      mss-network:
        aliases:
          - mss-elasticsearch
    labels:
      org.label-schema.group: "reporting"
    deploy:
      mode: global
      endpoint_mode: dnsrr
      resources:      
        limits:
          memory: 1G
      placement:
        constraints: [ node.hostname == pc-162 ]

  elasticsearch-master:
    image: elasticsearch:5.6.11
    hostname: mss-elasticsearch-master
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=mss-cluster
      - node.name=mss-elasticsearch-master
      - node.master=true
      - node.data=false
      - node.ingest=false
      #- bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=3
      - discovery.zen.ping.unicast.hosts=mss-elasticsearch-master
      - http_max_content_length=1204MB
    networks:
      mss-network:
        aliases:
          - mss-elasticsearch-master
    labels:
      org.label-schema.group: "reporting"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      resources:      
        limits:
          memory: 1G
      placement:
        constraints: [ node.hostname == pc-162 ]

  elasticsearch-data-1:
    image: elasticsearch:5.6.11
    hostname: mss-elasticsearch-data-1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=mss-cluster
      - node.name=mss-elasticsearch-data-1
      - node.master=false
      - node.data=true
      - node.ingest=false
      #- bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=3
      - discovery.zen.ping.unicast.hosts=mss-elasticsearch-master
      - http_max_content_length=1204MB
    volumes:
      - elasticsearch.data.1:/usr/share/elasticsearch/data
    networks:
      mss-network:
        aliases:
          - mss-elasticsearch-data-1
    labels:
      org.label-schema.group: "reporting"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: '0.1'
          memory: 1024M
        reservations:
          cpus: '0.05'
          memory: 128M
      placement:
        constraints: [ node.hostname == pc-162 ]
  
  elasticsearch-data-2:
    image: elasticsearch:5.6.11
    hostname: mss-elasticsearch-data-2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=mss-cluster
      - node.name=mss-elasticsearch-data-2
      - node.master=false
      - node.data=true
      - node.ingest=false
      #- bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=3
      - discovery.zen.ping.unicast.hosts=mss-elasticsearch-master
      - http_max_content_length=1204MB
    volumes:
      - elasticsearch.data.2:/usr/share/elasticsearch/data
    networks:
      mss-network:
        aliases:
          - mss-elasticsearch-data-2
    labels:
      org.label-schema.group: "reporting"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: '0.1'
          memory: 1024M
        reservations:
          cpus: '0.05'
          memory: 128M
      placement:
        constraints: [ node.hostname == pc-162 ]

