version: '3.3'

volumes:
  elasticsearch.data.1:
    external: true
  elasticsearch.data.2:
    external: true
  elasticsearch.master.1:
    external: true
  elasticsearch.master.2:
    external: true
networks:
  mss-network:
    external:
      name: mss-network

services:

  elasticsearch-coordinating:
    image: mss-elasticsearch:5.6.11
    hostname: mss-elasticsearch-coordinating
    environment:
      #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=mss-elasticsearch
      - bootstrap.memory_lock=true
      - "node.name=mss-elasticsearch-coordinating"
      - "node.master=false"
      - "node.data=false"
      - "node.ingest=false"
      - "network.host=0.0.0.0"
      - "discovery.zen.minimum_master_nodes=2"
      - "discovery.zen.ping.unicast.hosts=[mss-elasticsearch-master-1,mss-elasticsearch-master-2,mss-elasticsearch-master-3]"
    volumes:
      - ./elasticsearch/elasticsearch-coordinating.yml:/build/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/jvm-coordinating.options:/build/elasticsearch/config/jvm.options
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    networks:
      mss-network:
        aliases:
          - mss-elasticsearch-coordinating
    labels:
      org.label-schema.group: "reporting"
    deploy:
      mode: global
      endpoint_mode: dnsrr
      resources:      
        limits:
          memory: 1024M
        reservations:
          memory: 128M
      #placement:
      #  constraints: [ node.hostname == pc-162 ]
    healthcheck:
      test: wget -qO- http://localhost:9200 > /dev/null
      interval: 30s
      retries: 3
