version: '3.3'

networks:
  mss-network:
    external:
      name: mss-network

services:

  kibana:
    image: kibana:5.6.11
    hostname: mss-kibana
    environment:
      SERVER_HOST: "0.0.0.0"
      ELASTICSEARCH_URL: http://mss-elasticsearch-coordinating:9200
      SERVER_NAME: "mss-kibana.larion.com"
    ports:
      - "5601:5601"
    networks:
      mss-network:
        aliases:
          - mss-kibana
    labels:
      org.label-schema.group: "reporting"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 16M

    #  placement:
    #    constraints: [node.hostname == pc-162]
    healthcheck:
      test: wget -qO- http://localhost:5601 > /dev/null
      interval: 30s
      retries: 3




