version: '3'

networks:
  default:
      external:
        name: my-VLAN10

volumes:
    prometheus.data:
      external: true
    grafana.data:
      external: true

services:
  caddy:
    image: stefanprodan/caddy:latest
    #container_name: caddy
    ports:
      #- "3003:3003"
      - "9090:9090"
      - "9093:9093"
      - "9091:9091"
    volumes:
      - ./caddy/:/etc/caddy/
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    #restart: unless-stopped
    networks:
      default:
        aliases:
          - caddy
    labels:
      org.label-schema.group: "monitoring"
    deploy:
      mode: replicated
      replicas: 1
      #placement:
      #  constraints: [node.hostname == Docker-1]

